export const GETPROJECTS = 'GETPROJECTS'
export const INCLUDEPROJECTS = 'INCLUDEPROJECTS'
export const UPDATEPROJECTS = 'UPDATEPROJECTS'
export const REMOVEPROJECT = 'REMOVEPROJECTS'

export const GETTASKS = 'GETTASKS'
export const INCLUDETASK = 'ADDTASK'
export const UPDATETASK = 'ALTERTASK'